apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: course-enrollment
  name: course-enrollment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: course-enrollment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: course-enrollment
    spec:
      containers:
      - image: public.ecr.aws/m3r2x6z7/course_enrollment:latest
        imagePullPolicy: Always
        name: course-enrollment-image
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
    name: "course-enrollment-service"
spec:
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
    type: LoadBalancer
    selector:
        app.kubernetes.io/name: course-enrollment
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "course-enrollment-ingress"
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
    labels:
        app.kubernetes.io/name: courseEnrollment-ingress
spec:
    rules:
        - http:
            paths:
                - path: /*
                  backend:
                    serviceName: "course-enrollment-service"
                    servicePort: 8000
    